### PR TITLE
Test cases for UI testing, fixing issue #91, fixing issue #94

### PR DESCRIPTION
**Pull request by petbaik**
This pull fixes:

- Issue #94  Changes in workflow of generating wallet - private key is generate from seeds after cofirming them

- issue #91 

- actual import when enter seed phrases

- Writing test cases for basic functionalities made so far (I think more tests should be added while finishing the issues in this sprint)

- issue #90 

- Working on issue #46 and #34

### CODE REVIEW

**Comment by petbaik** [comment]
I return the aepp sdk version to 4, because I also notice that the identity_provider_poc  have older version

**Comment by petbaik** [comment]
When using sdk v.4 the postmessages doesn't work because @aeternity/aepp-sdk/es/provider/extension module is missing

**Comment by mradkov** [comment]
> When using sdk v.4 the postmessages doesn't work because @aeternity/aepp-sdk/es/provider/extension module is missing

Yes. It is not available in the v4 yet. The AEX-2 proposal was moved to final phase here (https://github.com/aeternity/AEXs/pull/34) but there are some issues that needs to be resolved before they accept the changes.

**Comment by mradkov** [comment]
Tests are failing due to `input[type=password]` missing.

image

**Comment by mradkov** [comment]
Merging.

**Pull request merged**
